[project]
name = "pycompanion"
version = "0.0.0"

dependencies = [
    "jsonschema"
]

[project.optional-dependencies]
websocket = [
    "websockets"
]

[tool.setuptools.package-data]
"pycompanion.liaison" = ["*.schema.json"]